[workspace]
resolver = "2"
members = ["algebra", "backend", "tensor"]


[workspace.package]
authors = ["Melnik <siarhei_melnik@proton.me>"]
edition = "2024"

[profile.release]
codegen-units = 1
lto = "thin"
